[algokit]
min_version = "v2.0.0"

[project]
type = "contract"
name = "startex-contracts"
artifacts = "smart_contracts/artifacts"

[project.run]
build = { commands = ["poetry run python -m smart_contracts build"], description = "Build all smart contracts in the project" }
audit-teal = { commands = [
  "algokit task analyze smart_contracts/artifacts --recursive --force --exclude rekey-to --exclude is-updatable --exclude missing-fee-check --exclude is-deletable --exclude can-close-asset --exclude can-close-account --exclude unprotected-deletable --exclude unprotected-updatable"
], description = "Audit TEAL files" }

[project.deploy]
# Genel (fallback) komut – herhangi bir ortam adı verilse de kullanılabilir
command = "poetry run python -m smart_contracts deploy"

[project.deploy.localnet]
# İstersen burada ayrı command yazabilirsin; yazmazsan yukarıdaki genel command kullanılır
environment_secrets = []

[project.deploy.testnet]
# Hata almamak için TESTNET için de açıkça command veriyoruz
command = "poetry run python -m smart_contracts deploy"
environment_secrets = ["DEPLOYER_MNEMONIC", "ALGOD_SERVER", "ALGOD_PORT", "ALGOD_TOKEN"]

[project.deploy.mainnet]
command = "poetry run python -m smart_contracts deploy"
environment_secrets = ["DEPLOYER_MNEMONIC", "ALGOD_SERVER", "ALGOD_PORT", "ALGOD_TOKEN"]