# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: 210205023@ostimteknik.edu.tr
author_name: ahmettahirmat
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: startex

